/**
 * Assignment definition, part 1: `assignments`, `assignment_sources`, `source_chunks`
 * (`06` sections 7.2.1-7.2.3; migration `0003_assignment_sources.sql`).
 *
 * Everything here is identity-free. `assignment_sources.storage_key` is opaque and
 * driver-relative, is generated by the writer rather than derived from the upload's filename,
 * and is never returned by an API (`06` section 6.9 rule 2, I-7).
 *
 * `source_chunks.text` is the verbatim extract. Nothing in this module rewrites it: ingestion
 * writes what the extractor produced, and the `char_count` is the character length of exactly
 * the string that is stored (`ck_source_chunks_char_count`).
 */

import type { Executor } from './courses';

/** `assignments.status` (`06` section 7.2.1). Distinct from every `publication_status`. */
export type AssignmentStatus = 'draft' | 'ingesting' | 'in_review' | 'published' | 'archived';

/** `assignment_sources.kind` (`06` section 7.2.2). */
export type SourceKind = 'brief' | 'rubric' | 'ai_policy' | 'marking_guide' | 'supplementary';

/** `assignment_sources.mime_type`, the O5 / D57 / D80 set. */
export type SourceMimeType =
  | 'application/pdf'
  | 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  | 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
  | 'image/png'
  | 'image/jpeg'
  | 'text/plain'
  | 'text/markdown';

export interface NewAssignment {
  readonly id: string;
  readonly courseId: string;
  readonly title: string;
  readonly status: AssignmentStatus;
  readonly dueAt: string | null;
  readonly createdByUserId: string;
  /** Non-null whenever `status = 'published'` (`ck_assignments_published_at`). */
  readonly publishedAt: string | null;
}

export interface NewAssignmentSource {
  readonly id: string;
  readonly assignmentId: string;
  readonly uploadedByUserId: string;
  readonly kind: SourceKind;
  /** Displayed to the tutor only. The `storage_key` is never derived from it. */
  readonly originalFilename: string;
  readonly storageKey: string;
  readonly mimeType: SourceMimeType;
  readonly byteSize: number;
  /** `null` for a format that has no pages, such as Markdown. */
  readonly pageCount: number | null;
  /** SHA-256 of the stored bytes, lower-case hex, exactly 64 characters. */
  readonly contentHash: string;
}

export interface NewSourceChunk {
  readonly id: string;
  readonly assignmentId: string;
  readonly sourceId: string;
  readonly chunkIndex: number;
  readonly text: string;
  readonly pageFrom: number | null;
  readonly pageTo: number | null;
  readonly sectionLabel: string | null;
  readonly charCount: number;
}

export async function insertAssignmentIfAbsent(
  ex: Executor,
  assignment: NewAssignment,
): Promise<boolean> {
  const rows = await ex<{ id: string }[]>`
    insert into assignments (
      id, course_id, title, status, due_at, created_by_user_id, published_at
    )
    values (
      ${assignment.id}::uuid,
      ${assignment.courseId}::uuid,
      ${assignment.title},
      ${assignment.status},
      ${assignment.dueAt}::timestamptz,
      ${assignment.createdByUserId}::uuid,
      ${assignment.publishedAt}::timestamptz
    )
    on conflict do nothing
    returning id
  `;
  return rows.length > 0;
}

/**
 * Point `assignments.current_structure_id` at the current structure (`06` section 7.2.1:
 * "maintained alongside `is_current`").
 *
 * The pair `assignments.current_structure_id` <-> `assignment_structures.assignment_id` is the
 * circular FK of trap T18, so the assignment row exists before the structure and this runs after
 * it. The `is null` guard is what makes the second seed run a no-op: without it the row would be
 * rewritten (and `set_updated_at()` would fire) on every run for no change.
 */
export async function linkCurrentStructure(
  ex: Executor,
  assignmentId: string,
  structureId: string,
): Promise<boolean> {
  const rows = await ex<{ id: string }[]>`
    update assignments
       set current_structure_id = ${structureId}::uuid
     where id = ${assignmentId}::uuid
       and current_structure_id is null
    returning id
  `;
  return rows.length > 0;
}

export async function insertSourceIfAbsent(
  ex: Executor,
  source: NewAssignmentSource,
): Promise<boolean> {
  const rows = await ex<{ id: string }[]>`
    insert into assignment_sources (
      id, assignment_id, uploaded_by_user_id, kind, original_filename, storage_key,
      mime_type, byte_size, page_count, content_hash, extraction_status
    )
    values (
      ${source.id}::uuid,
      ${source.assignmentId}::uuid,
      ${source.uploadedByUserId}::uuid,
      ${source.kind},
      ${source.originalFilename},
      ${source.storageKey},
      ${source.mimeType},
      ${source.byteSize},
      ${source.pageCount},
      ${source.contentHash},
      'extracted'
    )
    on conflict do nothing
    returning id
  `;
  return rows.length > 0;
}

export async function insertSourceChunkIfAbsent(
  ex: Executor,
  chunk: NewSourceChunk,
): Promise<boolean> {
  const rows = await ex<{ id: string }[]>`
    insert into source_chunks (
      id, assignment_id, source_id, chunk_index, text, page_from, page_to,
      section_label, char_count
    )
    values (
      ${chunk.id}::uuid,
      ${chunk.assignmentId}::uuid,
      ${chunk.sourceId}::uuid,
      ${chunk.chunkIndex},
      ${chunk.text},
      ${chunk.pageFrom},
      ${chunk.pageTo},
      ${chunk.sectionLabel},
      ${chunk.charCount}
    )
    on conflict do nothing
    returning id
  `;
  return rows.length > 0;
}
