/**
 * The migration runner: `pnpm db:migrate`.
 *
 * **Mechanism (decision D74).** `04` S2.1 says migrations are "generated by drizzle-kit and
 * committed under `src/lib/db/migrations/`", and `04` S2.3 rule 2 says `pnpm db:migrate`
 * runs "drizzle-kit"; `11` WP-01 requires this file as a "Migration runner over
 * `src/lib/db/migrations/*.sql`" together with a baseline file. Both requirements are
 * satisfied here: the committed `NNNN_slug.sql` files are the source of truth and this
 * runner applies them, while `drizzle-kit` stays a pinned dependency for
 * `drizzle-kit check`/`generate`. drizzle-kit is *not* the runner, because its journal
 * format cannot express what `06` section 6.3 mandates (`text` + named `CHECK` instead of
 * `CREATE TYPE`, partial unique indexes, a `DO` block, two views and a generated column)
 * without the SQL being hand-edited anyway -- and `04` S2.1's own stated rationale is
 * "plain SQL migrations a reviewer can read".
 *
 * Rules (`06` S6.7, `04` S3):
 * - Files are `NNNN_<short_description>.sql`, zero-padded, forward-only, one logical
 *   change per file, applied in ascending numeric order.
 * - **Immutable once applied.** The runner stores a SHA-256 of each applied file and
 *   refuses to continue if the bytes changed. That is what makes "the applied migration
 *   head" a fact rather than a convention (`04` S5.4, last line).
 * - Each file runs in its own transaction, then its ledger row is written inside that same
 *   transaction. A file that fails leaves neither schema changes nor a ledger row.
 *
 * Escaping the immutability guard during development is a **database reset**, not a ledger
 * edit:
 *
 *     drop schema public cascade;
 *     create schema public;
 *
 * Deleting the ledger row instead would let a second machine keep the old bytes while this
 * one advertises the new head.
 */

import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import postgres from 'postgres';

import { EXIT_CONFIG, ConfigError, getConfig } from '../config';
import { closeDb } from './client';

const FILE_PATTERN = /^(\d{4})_([a-z0-9]+(?:_[a-z0-9]+)*)\.sql$/;

/** Ledger table. Created by the runner, never by a migration file. */
const LEDGER_TABLE = 'schema_migrations';

export interface MigrationFile {
  /** Zero-padded numeric prefix, e.g. `0002`. */
  readonly version: string;
  /** Slug without the extension, e.g. `core`. */
  readonly name: string;
  readonly path: string;
  readonly checksum: string;
}

export interface MigrateResult {
  readonly applied: readonly string[];
  readonly alreadyApplied: readonly string[];
}

/** Locate `src/lib/db/migrations/` from both the source tree and a bundled runtime. */
export function migrationsDir(): string {
  const candidates: string[] = [];
  try {
    candidates.push(join(dirname(fileURLToPath(import.meta.url)), 'migrations'));
  } catch {
    // `import.meta.url` is unavailable only in a non-ESM context, which this app is not.
  }
  candidates.push(join(process.cwd(), 'src', 'lib', 'db', 'migrations'));
  candidates.push(join(process.cwd(), 'app', 'src', 'lib', 'db', 'migrations'));
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate;
  }
  const first = candidates[0];
  if (first === undefined) throw new Error('could not resolve the migrations directory');
  return first;
}

function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

/** Every migration file, ordered by version. Duplicate or malformed names abort. */
export async function listMigrations(directory: string = migrationsDir()): Promise<MigrationFile[]> {
  const entries = (await readdir(directory)).filter((entry) => entry.endsWith('.sql')).sort();
  const files: MigrationFile[] = [];
  const seen = new Map<string, string>();
  for (const entry of entries) {
    const match = FILE_PATTERN.exec(entry);
    if (match === null) {
      throw new Error(
        `migration file "${entry}" does not match NNNN_<short_description>.sql (06 section 6.7)`,
      );
    }
    const version = match[1] ?? '';
    const name = match[2] ?? '';
    const previous = seen.get(version);
    if (previous !== undefined) {
      throw new Error(
        `two migrations share version ${version}: "${previous}" and "${entry}"; versions are unique`,
      );
    }
    seen.set(version, entry);
    const path = join(directory, entry);
    files.push({ version, name, path, checksum: sha256(await readFile(path, 'utf8')) });
  }
  return files;
}

async function ensureLedger(sql: ReturnType<typeof postgres>): Promise<void> {
  await sql`
    create table if not exists ${sql(LEDGER_TABLE)} (
      version    text primary key,
      name       text not null,
      checksum   text not null,
      applied_at timestamptz not null default now()
    )
  `;
}

interface LedgerRow {
  version: string;
  checksum: string;
}

/**
 * Apply every pending migration, in order. Idempotent: a second run applies nothing and
 * reports the pending count as zero.
 */
export async function migrate(
  databaseUrl: string,
  log: (line: string) => void = () => undefined,
  directory: string = migrationsDir(),
): Promise<MigrateResult> {
  const files = await listMigrations(directory);
  const sql = postgres(databaseUrl, { max: 1, onnotice: () => undefined });
  const applied: string[] = [];
  const alreadyApplied: string[] = [];
  try {
    await ensureLedger(sql);
    const rows = await sql<LedgerRow[]>`select version, checksum from ${sql(LEDGER_TABLE)}`;
    const ledger = new Map(rows.map((row) => [row.version, row.checksum]));

    for (const file of files) {
      const label = `${file.version}_${file.name}`;
      const recorded = ledger.get(file.version);
      if (recorded !== undefined) {
        if (recorded !== file.checksum) {
          throw new Error(
            `migration ${label}.sql changed after it was applied (checksum mismatch). ` +
              'Migrations are immutable once applied (06 section 6.7). Add a new migration ' +
              'instead, or reset the database in development.',
          );
        }
        alreadyApplied.push(label);
        log(`skip  ${label} (already applied)`);
        continue;
      }

      const body = await readFile(file.path, 'utf8');
      await sql.begin(async (tx) => {
        // `.simple()` forces the simple query protocol, which is what allows one file to
        // hold several statements plus dollar-quoted function bodies.
        await tx.unsafe(body).simple();
        await tx`insert into ${tx(LEDGER_TABLE)} (version, name, checksum)
                 values (${file.version}, ${file.name}, ${file.checksum})`;
      });
      applied.push(label);
      log(`apply ${label}`);
    }

    log(
      applied.length === 0
        ? `no pending migrations (${alreadyApplied.length} already applied)`
        : `${applied.length} applied, ${alreadyApplied.length} already applied`,
    );
    return { applied, alreadyApplied };
  } finally {
    await sql.end({ timeout: 5 });
  }
}

export interface MigrationHead {
  readonly pending: readonly string[];
  readonly applied: readonly string[];
}

/**
 * Compare the repository migration head to what the database has applied. `04` S5.4, last
 * line: `pnpm start` aborts when they disagree, because "unknown Postgres state at deploy"
 * is a designed-against failure (`04` S12).
 */
export async function migrationHead(
  databaseUrl: string,
  directory: string = migrationsDir(),
): Promise<MigrationHead> {
  const files = await listMigrations(directory);
  const sql = postgres(databaseUrl, { max: 1, onnotice: () => undefined });
  try {
    await ensureLedger(sql);
    const rows = await sql<LedgerRow[]>`select version, checksum from ${sql(LEDGER_TABLE)}`;
    const ledger = new Map(rows.map((row) => [row.version, row.checksum]));
    const pending: string[] = [];
    const applied: string[] = [];
    for (const file of files) {
      const label = `${file.version}_${file.name}`;
      const recorded = ledger.get(file.version);
      if (recorded === undefined) pending.push(label);
      else applied.push(label);
    }
    for (const version of ledger.keys()) {
      if (!files.some((file) => file.version === version)) {
        pending.push(`${version}_<present in database, absent from repository>`);
      }
    }
    return { pending, applied };
  } finally {
    await sql.end({ timeout: 5 });
  }
}

async function main(): Promise<void> {
  const config = getConfig();
  const checkOnly = process.argv.includes('--check');
  if (config.databaseUrl === null) {
    process.stderr.write('CONFIG_INVALID: DATABASE_URL\n');
    process.exit(EXIT_CONFIG);
  }
  const url = config.databaseUrl;
  const log = (line: string): void => {
    process.stdout.write(`${line}\n`);
  };

  if (checkOnly) {
    const head = await migrationHead(url);
    if (head.pending.length > 0) {
      process.stderr.write(
        `MIGRATION_HEAD_MISMATCH: ${head.pending.length} migration(s) not applied: ` +
          `${head.pending.join(', ')}\n`,
      );
      process.exit(EXIT_CONFIG);
    }
    log(`migration head matches (${head.applied.length} applied)`);
    return;
  }

  await migrate(url, log);
}

const invokedPath = process.argv[1] ?? '';
const selfPath = (() => {
  try {
    return fileURLToPath(import.meta.url);
  } catch {
    return '';
  }
})();

const isDirectRun =
  invokedPath !== '' &&
  (invokedPath === selfPath ||
    invokedPath.replace(/\\/g, '/').endsWith('/src/lib/db/migrate.ts'));

if (isDirectRun) {
  main()
    .then(() => closeDb())
    .catch((error: unknown) => {
      if (error instanceof ConfigError) {
        process.stderr.write(`${error.message}\n`);
        process.exit(EXIT_CONFIG);
      }
      process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
      process.exit(1);
    });
}
